/// Flutter icons CustomStopWatch
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomStopWatch
///      fonts:
///       - asset: fonts/CustomStopWatch.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomStopWatch {
  CustomStopWatch._();

  static const _kFontFam = 'CustomStopWatch';
  static const String? _kFontPkg = null;

  static const IconData stopwatch = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
